---
- hosts: testbox
  become: true
  tasks:
    - name: remove unwanted packages
      apt:
        state: absent
        name:
          - unattended-upgrades
          - snapd
    - name: install java 11 jdk and screen and rsync
      apt:
        name:
          - screen
          - rsync
          - openjdk-11-jdk-headless
    - name: Install docker on ubuntu
      import_tasks: install-docker-playbook.yml
    - name: copy k6 directory
      ansible.posix.synchronize:
        src: ../../k6
        dest: /home/splunk/
    - name: copy project src directory
      ansible.posix.synchronize:
        src: ../../src
        dest: /home/splunk/
    - name: copy gradle directory
      ansible.posix.synchronize:
        src: ../../gradle
        dest: /home/splunk/
    - name: copy gradle settings
      ansible.posix.synchronize:
        src: ../../settings.gradle.kts
        dest: /home/splunk/
    - name: copy gradle build script
      ansible.posix.synchronize:
        src: ../../build.gradle.kts
        dest: /home/splunk/
    - name: copy gradle wrapper
      ansible.posix.synchronize:
        src: ../../gradlew
        dest: /home/splunk/
    - name: copy run10 script
      ansible.builtin.template:
        src: run10.sh.jinja
        dest: /home/splunk/run10.sh
        owner: splunk
        group: users
        mode: 0755
    - name: chown copied files
      ansible.builtin.command:
        cmd: 'chown -R splunk:users k6 src gradle build.gradle.kts gradlew settings.gradle.kts'
    - name: run the build
      become: yes
      become_user: splunk
      ansible.builtin.command:
        cmd: ./gradlew compileTestJava
