name: run overhead tests
on:
  workflow_dispatch:

jobs:
  run-overhead-tests:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2.3.4
      - name: checkout
        uses: actions/checkout@v2.3.4
        with:
          ref: gh-pages
          path: gh-pages
      - name: copy results from gh-pages branch
        run: |
          rsync -avv gh-pages/results/ results/ && rm -rf gh-pages
      - name: run tests
        run: ./gradlew test
        working-directory: .
      - name: inspect the results dir
        run: |
          ls -l results
      - name: commit updated results
        uses: EndBug/add-and-commit@v7
        with:
          add: results/
          branch: gh-pages
          message: update test result data
          file_pattern: results