name: run overhead tests
on:
  workflow_dispatch:

jobs:
  run-overhead-tests:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2.3.4
      - name: checkout
        uses: actions/checkout@v2.3.4
        with:
          ref: gh-pages
          path: gh-pages
      - name: copy results from gh-pages branch
        run: |
          rsync -avv gh-pages/results/ results/ && rm -rf gh-pages
      - name: run tests
        run: ./gradlew test
        working-directory: .
      - name: commit updated results
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: gh-pages
          commit_message: update test result data
          file_pattern: results