name: run overhead tests
on:
  workflow_dispatch:

jobs:
  run-overhead-tests:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2.3.4
      - name: checkout
        uses: actions/checkout@v2.3.4
        with:
          ref: gh-pages
          path: gh-pages
      - name: copy results from gh-pages branch
        run: |
          rsync -avv gh-pages/results/ results/
      - name: run tests
        run: ./gradlew test
        working-directory: .
      - name: inspect the results dir
        run: |
          ls -lR results
      - name: copy results back to gh-pages branch
        run: |
          rsync -avv results/ gh-pages/results/ && rm -rf results
      - name: commit updated results
        uses: EndBug/add-and-commit@v7
        with:
          add: 'results'
          cwd: './gh-pages'
          branch: 'gh-pages'
          message: 'update test result data'
